name: Build

on:
  push:
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  CC: clang

jobs:
  build:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: cargo build --verbose
      - run: cargo test --verbose
